skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  
  <body>
    <% if logged_in? %>
      <h1>Welcome,&nbsp<%=current_user.user_name%> </h1>
      <!-- logout button only --> 
      <form action="<%= session_url %>" method="post"> 
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Logout"> 
      </form>
    <% else %>
      <!-- login and sign up button --> 
      <form action="<%= new_session_url %>" method="get"> 
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="Login"> 
      </form>
      <!-- <a href="<%#= new_session_url %>">LOGIN</a> -->
      <!-- <a href="<%#= new_user_url %>">SIGN UP</a> -->
      <form action="<%= new_user_url %>" method="get"> 
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="Sign Up"> 
      </form>
    <% end %>
    <% if flash.now[:errors] %>
      <% flash.now[:errors].each do |error|%>
        <%= error %>
      <% end%>
    <% end%>
    <%= yield %>
  </body>
</html>